<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <style type="text/css">
        table {
            font-family: verdana,arial,sans-serif;
            font-size:11px;
            color:#333333;
            border-width: 1px;
            border-color: #666666;
            border-collapse: collapse;
        }
        table th {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #dedede;
        }
        table td {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #ffffff;
        }
    </style>
</head>
<body>
    <img id="imgLoader" src="../../public/images/ajax-loader.gif" width="20px" height="20px"/>
    <table id="tblServices" cellpading="10" style="display:none;">
        <thead>
            <th>Vehicle Model</th>
            <th>Plates</th>
            <th>Service status</th>
            <th>Driver Name</th>
            <th>User</th>
            <th>Target Address</th>
        </thead>
        <tbody>
        </tbody>
    </table>
    <script type="text/javascript">

        $(document).ready(function () {
            loadServices();
        })

        function loadServices() {

            $.ajax({
                url: 'services',
                type: 'GET',
                dataType: 'json',
                success: function( services ) {
                    $("#imgLoader").hide();

                    $table = $("#tblServices");
                    $table.show();

                    $.each(services, function (index, service) {

                        $table.find("tbody").append(
                            $("<tr></tr>").append(
                                $("<td></td>").html(service.vehicle.model)
                            ).append(
                                $("<td></td>").html(service.vehicle.plates)
                            ).append(
                                $("<td></td>").html(service.status)
                            ).append(
                                $("<td></td>").html(service.vehicle.driver.name)
                            ).append(
                                $("<td></td>").html(service.user)
                            ).append(
                                $("<td></td>").html(service.targetAddress)
                            )
                        );
                    });
                },
                beforeSend: setHeader
            });

            function setHeader(xhr) {
                xhr.setRequestHeader('Accept', 'application/json');
            }
        }
    </script>
</body>
</html>