<html>
<head>
    <style type="text/css">
        table {
            font-family: verdana,arial,sans-serif;
            font-size:11px;
            color:#333333;
            border-width: 1px;
            border-color: #666666;
            border-collapse: collapse;
        }
        table th {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #dedede;
        }
        table td {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #ffffff;
        }
    </style>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
</head>
<body>
    <img id="imgLoader" src="../../public/images/ajax-loader.gif" width="20px" height="20px"/>

    <table id="tblServices" cellpading="10" style="display:none;">
        <thead>
            <th>Status</th>
            <th>Vehicle Model</th>
            <th>Plates</th>
            <th>Driver Name</th>
        </thead>
        <tbody>
        </tbody>
    </table>
    <script type="text/javascript">

        $(document).ready(function () {
            loadServices();
        })

        function loadServices() {

            $.ajax({
                url: 'taxis',
                type: 'GET',
                dataType: 'json',
                success: function( vehicles ) {
                    $("#imgLoader").hide();

                    $table = $("#tblServices");
                    $table.show();
                    $body = $table.find("tbody");

                    $.each(vehicles, function (index, vehicle) {

                        var driverName = "";

                        if (typeof vehicle.driver !== "undefined" && vehicle.driver != null) {
                            driverName = vehicle.driver.name;
                        }

                        var imgUrl;
                        var statusTitle;

                        if (vehicle.status == "ACTIVE") {
                            imgUrl = "check_circle";
                            statusTitle = "ACTIVE";
                        } else {
                            imgUrl = "block";
                            statusTitle = "BLOCKED";
                        }

                        var statusTag = $("<i></i>").addClass("material-icons").html(imgUrl).attr("title", statusTitle);
                        statusTag.click(function() {

                            var newStatus = "";
                            if (statusTag.attr("title") == "ACTIVE") {
                                newStatus = "BLOCKED";
                                statusTag.html("block");
                            } else {
                                newStatus = "ACTIVE";
                                statusTag.html("check_circle");
                            }
                            statusTag.attr("title", newStatus);

                            $.ajax({
                                url: "taxis",
                                dataType: "json",
                                contentType: "application/json",
                                data: JSON.stringify({ "idTaxi":  vehicle.objectId , "status":  newStatus }),
                                type: "put",
                                success: function(result) {
                                }
                            });
                        });

                        $body.append(
                            $("<tr></tr>").append(
                                $("<td></td>").attr("align", "center").append(statusTag)
                            ).append(
                                $("<td></td>").html(vehicle.model)
                            ).append(
                                $("<td></td>").html(vehicle.plates)
                            ).append(
                                $("<td></td>").html(driverName)
                            )
                        );

                    });
                },
                beforeSend: setHeader
            });

            function setHeader(xhr) {
                xhr.setRequestHeader('Accept', 'application/json');
            }
        }
    </script>
</body>
</html>